service: chatgpt-slackbot
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  memorySize: 512
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
